### ISSUE TITLE
Document.hasFocus() always returns true when print dialog is opened in Edge on Windows 10

### ISSUE THREAD

**Issue by Yan-corps** [MicrosoftDocs/edge-developer#1062]
Hi, 
I was trying to use window.setInterval() API to check the result of **document.hasfocus()**. 
Normally, when we click to another browser tab or another application, the document.hasfocus() of one page will return **false**. 
However, when I tried to print a webpage in Edge, and **with the print dialog opened, I found the document.hasfocus() always returns true**, and it shouldn't be, cause the print dialog doesn't belong to the webpage. This only happens on **Windows platform**(It works fine on Edge for Mac). In fact, this also happens on Chrome for Window10

The repro steps:
1. Open any webpage with Edge.
2. Open devtools and keep checking document.hasFocus().
3. Print the webpage and shows the print dialog of Edge.
4. document.hasFocus() always show true no matter where we click to(another tab or another application).

I am not sure whether this is a bug of Edge, so I think I should submit an issue here to seek for some help. Any workaround that can fix this? Thanks in advance for your kind help.

**Comment by captainbrosset** [comment]
Hi @Yan-corps and apologies for the late reply. 
I tested your repro steps on Edge (current stable release, 91) but could not see the problem.

I opened DevTools (undocked), entered `setInterval(() => {console.log(document.hasFocus())}, 1000)` in the console in order to have a log of the value every second, then verified that this working well by clicking in the page, and switching to other apps. When I, then, opened the print dialog (by pressing ctrl+P), I was only seeing `false` in the console. It also went back to `true` when I dismissed the dialog.

Would you mind trying again and see if it works for you too now?

>I am not sure whether this is a bug of Edge, so I think I should submit an issue here to seek for some help. 

This does sound like an Edge bug indeed, while this repository is about the Microsoft Docs website. Next time, you can use the feedback icon in Edge directly (you can find it in the main menu button, shown below) to send questions or report bugs.

![image](https://user-images.githubusercontent.com/1152698/125436366-129f95c3-443f-4847-b353-8d2528268d5a.png)
