### ISSUE TITLE
The WebView2 instructions on this page do not work

### ISSUE THREAD

**Issue by Javaman2** [MicrosoftDocs/edge-developer#1088]
Environment:
.NET Framework 4.7.2

**Visual Studio**

Microsoft Visual Studio Professional 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA961
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.557.25636
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.557.25636
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.557.25636
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.557.25636
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.5.20902.1 Commit Hash:b474efcb6f92db52a8f8e2e6a8cb9648476885cc
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62012.31170
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

**XAML**
```
<Window x:Class="WpfApp3.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        xmlns:local="clr-namespace:WpfApp3"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <DockPanel>
        <wv2:WebView2 Name="webView"
                      Source="https://www.bing.com"
                
    />
    </DockPanel>
</Window>
```
**Installed NuGet Package**

![image](https://user-images.githubusercontent.com/3665510/106677596-a0068a80-657e-11eb-9131-1fe9d6f6c38b.png)

To recreate just follow the instructions on this page to add a webview2 to a WPF Application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9dc9d2-795c-9612-3585-408b4621c080
* Version Independent ID: f73fc16d-d842-4507-9fdb-b42856720355
* Content: [Getting started with WebView2 for WPF apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf)
* Content Source: [microsoft-edge/webview2/gettingstarted/wpf.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/wpf.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Closing this issue because an issue was opened on the engineering feedback repo. Thanks.

**Comment by champnic** [comment]
@Javaman2 Can you verify that you have the prerequisites?
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf#prerequisites

Specifically, you need the stable WebView2 Runtime or a Microsoft Edge Dev, Canary, or Beta channel installed on your machine.

**Comment by Predatorie** [comment]
I am experiencing the same issue as the original poster. Followed the example posted online, project builds fine no errors or warnings, however a blank view is displayed at runtime.

File New -> WPF App and followed the example at https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf

![image](https://user-images.githubusercontent.com/2666052/112043505-1e16f480-8b1f-11eb-9c6e-7ba05b87154a.png)

![image](https://user-images.githubusercontent.com/2666052/112044034-b57c4780-8b1f-11eb-9a24-fa993efc04ee.png)

![image](https://user-images.githubusercontent.com/2666052/112043524-23743f00-8b1f-11eb-9cc2-ff0d11fb58ea.png)

![image](https://user-images.githubusercontent.com/2666052/112043358-f4f66400-8b1e-11eb-8a61-10d5e978309c.png)

**Comment by champnic** [comment]
@Predatorie Can you verify that you have the prerequisites?
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf#prerequisites

Specifically, you need the stable WebView2 Runtime or a Microsoft Edge Dev, Canary, or Beta channel installed on your machine (not Microsoft Edge Stable). If you do have it installed, can you let me know what version you have?

**Comment by Predatorie** [comment]
@champnic 

I must have read and re-read the prerequisites several times and I assumed adding the nuget was sufficient. Upon checking my machines registry key for HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5} it appears the runtime is not installed. 

I have a ticket into our IT department to allow me to download and install the runtime and then I can verify, 

Thank you your time,

**Comment by Predatorie** [comment]
@champnic 

I was able to download and install the runtime. I created a simple WPF application to test (following the example) and that works as expected, however, my use case is a little different and after some additional testing I may have discovered a potential issue.

For context, we ship a desktop application that exposes our  .NET API allowing customers to create add-ins using C# or VB.NET. Our desktop application is typically installed under Program Files and an Add-Ins folder is created under the users My Documents folder.

To run an add-in the customer has created the workflow is, run the desktop application and click the Run Add-In button to select the add-in to execute located in the add-ins folder under My Documents.

I created a simple WPF add-in with a view following along with the example mentioned earlier in this thread (the same as I used in my WPF application test) but I was presented with the following message:

![image](https://user-images.githubusercontent.com/2666052/112242219-cad99a80-8c21-11eb-98fe-dd087b7a4d7a.png)

I even went as far as manually creating the folder 'EBWebView' and set read only off  to see if I could get beyond the error message and have the webview render the page but nothing was displayed in the view and no further errors appeared.

It appears, per the message, that the webview is trying to write to program files and fails because our customers do not typically run with elevated permissions, they should not be creating anything under program files. I would have expected Edge to write to the location of the add-in (that contains the webview) and not the 'host' application?

Let me know if you need any further information. I do realize this might be a bit of an edge case (no pun intended)

**Comment by champnic** [comment]
@Predatorie It's fine to continue the discussion here :) If we discover a bug we need to go fix or a feature request I can move that comment into a new Feedback repo issue.

For the User Data Folder, you can specify a better location for it (like somewhere in your add-ins directory) when creating the CoreWebView2Environment. This would use the explicit initialization path (create environment, then use `WebView2.EnsureCoreWebView2Async(env)`), instead of just setting the `WebView2.Source` property.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.774.44#Microsoft_Web_WebView2_Core_CoreWebView2Environment_CreateAsync_System_String_System_String_Microsoft_Web_WebView2_Core_CoreWebView2EnvironmentOptions_

This doc may have other useful info around the User Data Folder:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder

Let me know if that works for you!

**Comment by Predatorie** [comment]
@champnic ah, I see, I ran with defaults just setting the source. I'll revisit this tomorrow and get back to you.

Thanks again.

**Comment by Predatorie** [comment]
@champnic 

I have had additional time to do some testing. Unfortunately I am still unable to successfully display the WebView2 control in my WPF assembly that is loaded by our desktop application.

I am setting the user data folder in my class library as shown below but Edge still tries to create the folder where the exe (host) is running and not where the assembly is located.

My test code:
![image](https://user-images.githubusercontent.com/2666052/112620928-8146a680-8dff-11eb-92da-e208c1927486.png)

Same error:
![image](https://user-images.githubusercontent.com/2666052/112620945-87d51e00-8dff-11eb-8664-85fc7bda51b8.png)

From the docs:
![image](https://user-images.githubusercontent.com/2666052/112620968-902d5900-8dff-11eb-9948-9aaa692d7dad.png)

I assume that Edge is looking for an exe only and not a simple class library that is my test add-in? I am not sure where to go from here.

Thanks.

**Comment by champnic** [comment]
It should be trying to use the userDataFolder you passed in `C:\Users\...`. Is the error message for the folder you manually created? Can you try deleting that folder?

**Comment by Predatorie** [comment]
@champnic 

I wrapped a try catch around the InitializeAsync method by way of the Task extension, the error is not very helpful.
![image](https://user-images.githubusercontent.com/2666052/112853981-64b6a280-907b-11eb-87c5-c2c4100c50f6.png)

No folder is created under the exe folder as expected because I am setting the userDataFolder, however, no folder is created where I am setting the userFolderData path. The same path where my add-in is located that contains the WebView2..

**Comment by champnic** [comment]
We are actively working on improving the error message and making the UDF experience better here.

Access Denied is nearly always related to creating the User Data Folder. Is the "Mastercam\Add-Ins" folder protected in some way? Are you logged in to the same user that created and owns that folder? Could you try something like creating "C:\temp" and using that for the UDF?

**Comment by Predatorie** [comment]
@champnic 

I have tried running as the same user and as Admin with same results. I have also tried with a temp folder with the same results.

**Comment by DavidShoe** [comment]
@Predatorie  Can you please install process monitor https://docs.microsoft.com/en-us/sysinternals/downloads/procmon and configure it to filter for process name = "your process name" and process name = "msedgewebview2.exe".  What we want to see is what exactly the directory is that is getting the access denied.

**Comment by Predatorie** [comment]
@DavidShoe I have installed and configured Process Monitor per your request, If I add my add-in (WebView2Tests.dll) to the filter with the msedgewebview2.exe nothing is displayed in the results. Once I add our application, mastercam.exe that will load and execute my add-in I get a lot of information but I am not sure what it is I am looking for.
