### ISSUE TITLE
Request to correct UserAgentOverride list on gyao.yahoo.co.jp

### ISSUE THREAD

**Issue by narirou** [MicrosoftDocs/edge-developer#1163]
Hi, Edge team! ✋
I am an engineer for Yahoo! JAPAN and a website owner for [gyao.yahoo.co.jp](https://gyao.yahoo.co.jp/).

We have a question about the features of [UserAgentOverride](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-string#user-agent-overrides).

Currently, GYAO's service receives a lot of emails saying that DRM videos cannot be viewed on the Edge browser.

After investigating, UserAgentOverride function overwrites the UserAgent when browsing gyao.yahoo.co.jp.

Where can we request to stop this overwrite?
Also, we were not aware of this change notice, where will it be sent?

Thank you.

![override (1)](https://user-images.githubusercontent.com/2879935/112585928-1ff1f800-8e3e-11eb-9513-22bd00eccbe7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e0130ae-2318-e95c-a77d-669d2c5dc8b8
* Version Independent ID: 3fcc0df5-94ed-6a3d-5c3f-78229329288c
* Content: [Microsoft Edge User Agent String - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-string)
* Content Source: [microsoft-edge/web-platform/user-agent-string.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/web-platform/user-agent-string.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by jennynotjen** [comment]
Hi there, thanks for reaching out. It looks like your site was accidentally added to our User Agent override list due to an error – sorry about that! We’ve removed it from the list and DRM videos should be working as normal. 

To understand how we can prevent video playback issues in the future, could you share whether you're using a specific media playback library that relies on Chrome UA detection? And if so, which one (custom, vendor, open source, etc.)?

Thanks!
Jenny from Edge Platform Team

**Comment by jennynotjen** [comment]
Hi @narirou, thanks for reaching out. It looks like your site was accidentally added to our User Agent override list due to an error – sorry about that! We’ve removed it from the list and DRM videos should be working as normal.

To understand how we can prevent video playback issues in the future, could you share whether you're using a specific media playback library that relies on Chrome UA detection? And if so, which one (custom, vendor, open source, etc.)?

Thanks!
Jenny from Edge Platform Team

**Comment by narirou** [comment]
Hi, jennynotjen, Thank you for your support.
After the change, we will make sure that it works and that the number of user inquiries is reduced.

> could you share whether you're using a specific media playback library that relies on Chrome UA detection

Currently we mainly use two types of players in a production environment.

- 1. video.js with videojs-contrib-eme (Brightcove)
- 2. Dash.js

We also use [platform.js](https://www.npmjs.com/package/platform) to identify the UA and include workaround processing to fix playback glitches.

**Comment by Reezaali** [comment]
I'll proceed to close this issue now. Thanks.
