### ISSUE TITLE
System.MissingMethodException: 'Method not found: 'OpenQA.Selenium.Remote.DesiredCapabilities OpenQA.Selenium.DriverOptions.GenerateDesiredCapabilities(Boolean)'.'

### ISSUE THREAD

**Issue by hhoangnl** [MicrosoftDocs/edge-developer#1176]
I followed the example, not sure why I get an exception:

System.MissingMethodException: 'Method not found: 'OpenQA.Selenium.Remote.DesiredCapabilities OpenQA.Selenium.DriverOptions.GenerateDesiredCapabilities(Boolean)'.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37d6441-bb7b-8842-314d-1fe929bd9aa3
* Version Independent ID: b3833510-5a57-cb23-51d0-f8df10ca9e71
* Content: [Use WebDriver (Chromium) for test automation - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=c-sharp)
* Content Source: [microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by bwalderman** [comment]
Hi @hhoangnl. Can you please copy/paste the complete example you followed? Please also state which Selenium version you are using.

**Comment by AbdulqadirJ** [comment]
i am getting same error while using Selenium version 4.0.0beta2
on creating new EdgeDriver with Userdata path and EdgeOptions
webD = new EdgeDriver(pathData, EdgeOptionsD);

**Comment by bwalderman** [comment]
@AbdulqadirJ, @hhoangnl, this error can happen if you attempt to use Microsoft.Edge.SeleniumTools with Selenium 4. 

Microsoft.Edge.SeleniumTools is for Selenium 3 only and you do not need to use it with Selenium 4 because Selenium 4 already supports Chromium Edge.

Please remove Microsoft.Edge.SeleniumTools from your project and ensure you are using the official `EdgeOptions` and `EdgeDriver` classes from the `OpenQA.Selenium.Edge` namespace.

Hope this helps!
