### ISSUE TITLE
Mobile view unreadable in WebView2 Benefits section

### ISSUE THREAD

**Issue by noahsb** [MicrosoftDocs/edge-developer#1311]
Hi! When reading the docs under the [WebView2 Benefits section](https://docs.microsoft.com/en-us/microsoft-edge/webview2/#webview2-benefits), I found it difficult to read using a mobile device. This is a clear layout bug for mobile viewports as the desktop view looks much different (and is readable). Below are screenshots to show the issue:

Desktop view:
<img width="795" alt="Screen Shot 2021-06-26 at 12 05 22 PM" src="https://user-images.githubusercontent.com/49932437/123520527-cab0c700-d676-11eb-874f-a942b8be4b37.png">

Mobile view:
<img width="339" alt="Screen Shot 2021-06-26 at 12 05 56 PM" src="https://user-images.githubusercontent.com/49932437/123520545-def4c400-d676-11eb-87d1-0f0dde964d28.png">

Happy to contribute to this fix if desired - thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6a3fc4-ae92-1353-9600-a6547082b1e2
* Version Independent ID: abdf9451-f4ba-5b3f-f516-c5d0361d2d32
* Content: [Microsoft Edge WebView2 Control - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/)
* Content Source: [microsoft-edge/webview2/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/index.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for filing this, and apologies for the long delay replying.
I believe this has been fixed since you reported the issue. I tested today on mobile and the layout seems to wrap correctly. See below:

![mobile](https://user-images.githubusercontent.com/1152698/142891867-92cf06a5-5a9b-46a8-9ed8-8efb0ebf9a4d.jpg)

Closing this issue based on the above. Please feel free to re-open if the problem persists.
