### ISSUE TITLE
扩展组件好像没有

### ISSUE THREAD

**Issue by teamor3334** [MicrosoftDocs/edge-developer#1325]
Vue.js devtools

**Comment by Reezaali** [comment]
Hi @teamor3334 - can you provide a link to the extension please?

**Comment by captainbrosset** [comment]
I believe this issue is about the Vue.js DevTools extension missing from the Edge extension store. This is a common request that the Edge DevTools team receives on a regular basis. Indeed, the Vue.js extension authors only made the extension available on Firefox and Chrome.

That said, the Chrome webstore version of it can be installed on Edge too: https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd

It would be great if the extension was also present on the Microsoft Edge store, and I will follow-up with the right teams to make that happen, but this isn't a docs problem, so I'll close this issue.

**Comment by captainbrosset** [comment]
Oh, one thing I hadn't thought of is that the chrome webstore version can't be installed on Edge if you're in China and don't have a VPN.

I found the issue on the Vue.JS DevTools repo tracking this: https://github.com/vuejs/devtools/issues/1155
