### ISSUE TITLE
DevTool dont evalueate \r\n character in Console tab

### ISSUE THREAD

**Issue by lantran2019** [MicrosoftDocs/edge-developer#1338]
I execute the script script:
`text = "";
for(i = 0; i < 10; i++) 
   text+= i + "\r\n";`
But result is: 
`0\r\n1\r\n2\r\n3\r\n4\r\n5\r\n6\r\n7\r\n8\r\n9\r\n`

My expectation is:
0
1
2
...
9
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e2efb18-3126-dc51-500f-c3e6b8b9d824
* Version Independent ID: 894a7544-0e73-3508-310c-bf9552bf864d
* Content: [The Console as a JavaScript environment - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/console/console-javascript)
* Content Source: [microsoft-edge/devtools-guide-chromium/console/console-javascript.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/console/console-javascript.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reporting this. It is indeed a bit of a strange behavior. Unfortunately it is by design at the moment. This also works the same in Chrome and in NodeJS.

There was a recent Chromium change documented in this explainer with more information about it: 
https://docs.google.com/document/d/1F1sO0B0rZjr_CQmbsGpiRcuBD7uFytCUWiDlUiJ5eus/edit

And the work happened in this bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1208389

It's worth noting that you can right-click on the result and choose "copy string contents" to copy the string without the escaped characters.

Feel free to file an issue on https://bugs.chromium.org if you would like to discuss a change.
