### ISSUE TITLE
Enable Safari Web Extensions on Edge IOS

### ISSUE THREAD

**Issue by ToFab** [MicrosoftDocs/edge-developer#1482]
With IOS 15 it is now possible to use Safari Web Extensions together with the Safari browser on IOS. 
https://developer.apple.com/documentation/safariservices/safari_web_extensions

The same support should be added to Edge on IOS since Safari and Edge share the same engine.

**Comment by captainbrosset** [comment]
Thank you for the proposal. This repository is for the documentation of the Edge developer features, not for the features themselves. So could you please submit this feedback with the following instructions instead? I'll close this issue now since it does not have an actionable documentation change.

To submit Edge feedback:

* Click the **Settings and more** button in the top-right corner of the browser (the button looks like three dots `...`).
* Go to the **Help and feedback** menu.
* Click **Send feedback**.
* In the window that appears, type in your feedback and then press send.

Thanks!
