### ISSUE TITLE
Issue with Edge driver- WebDriverException: unknown error: MSEdge failed to start: was killed

### ISSUE THREAD

**Issue by jitendrakalyan** [MicrosoftDocs/edge-developer#1587]
Hi, 
We run a suite of tests on Selenium Grid version 3 (3.141.59) using Edge Driver. We are seeing an issue since Edge browser 95 was released. Seeing this 96 as well. We have made sure we are using matching driver versions for the browser.

First we are getting an error mentioned in the stackoverflow issue below. 
https://stackoverflow.com/questions/66682566/ms-edge-driver-error-devtoolsactiveport-file-doesnt-exist-works-only-with

After we tried adding the following we are seeing  "unknown-error-msedge-failed-to-start-was-killed" as mentioned in another stackoverflow page referenced below. Can you please provide any guidance on solving the issue? 

options.getEdgeOptions().setHeadless(true);
        options.getEdgeOptions().addArguments("--disable-extensions"); // disabling extensions
        options.getEdgeOptions().addArguments("--disable-gpu"); // applicable to windows os only
        options.getEdgeOptions().addArguments("--disable-dev-shm-usage"); // overcome limited
                                                                          // resource
                                                                          // problems
        options.getEdgeOptions().addArguments("--no-sandbox"); // Bypass OS security model
        options.getEdgeOptions().addArguments("--remote-debugging-port=9222");

https://stackoverflow.com/questions/69770506/webdriverexception-unknown-error-msedge-failed-to-start-was-killed/70061533#70061533

**Comment by captainbrosset** [comment]
Hi @jitendrakalyan, unfortunately this repository is here to track documentation issues, not issues with webdriver itself.
The webdriver team is part of the DevTools team, so one good way to reach out to them is to go through the DevTools feedback channel. I therefore suggest you to send this message via DevTools by doing:

* open Edge DevTools,
* click the Send Feedback button (near the top-right corner in DevTools) or press alt+shift+I

This will make sure your issue is routed to the right place. Thanks!

**Comment by jitendrakalyan** [comment]
@captainbrosset thank you for letting me know. I have submitted the issue through the feedback channel.
