### ISSUE TITLE
How do we know when these endpoints are public?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/edge-developer#1611]
Hi,

I'm using github actions to publish my extension to google's chrome webstore.  I would like to do the same with Edge, but the API is not available yet.  How will we know when the proposed API endpoints in this document are available to the public?

Thanks!
Mark

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f22ef0a-202d-482d-be95-1a772c2addc9
* Version Independent ID: 1a2f5a98-fbb2-ce6b-698c-09b3d878f168
* Content: [Using the Microsoft Edge Add-ons API - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api)
* Content Source: [microsoft-edge/extensions-chromium/publish/api/using-addons-api.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/publish/api/using-addons-api.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. I don't know whether this has been planned yet, since the API is still under development. But I expect that the documentation page you refer to will be updated, and that a blog post will be added to the [MS Edge Dev blog](https://blogs.windows.com/msedgedev/), at least.

@ashishnirvana1 might be able to share some information related to timeframe here.

**Comment by mikehoffms** [comment]
See https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/whats-new/roadmap
