### ISSUE TITLE
Handle "disable popup blocker" does not work in Edge with IE-Mode

### ISSUE THREAD

**Issue by hendryang** [MicrosoftDocs/edge-developer#1674]
Hi Team,

I'm not able to find any details or known problem when dealing with pop-ups in Edge with IE-Mode. I've originally logged the issue here -> https://github.com/SeleniumHQ/selenium/issues/10221 with various attempt to enable the pop-ups but it seems to be not possible as of now.

Appreciate any workaround or probably updated document if it's not supported. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9fa537-f960-f6f9-a39f-5ea14b41f01f
* Version Independent ID: de9fa537-f960-f6f9-a39f-5ea14b41f01f
* Content: [Use Internet Explorer Driver to automate IE mode in Microsoft Edge - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode?tabs=c-sharp#known-limitations)
* Content Source: [microsoft-edge/webdriver-chromium/ie-mode.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/ie-mode.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. I don't know about this, so I'm attempting to find out more and will report back here. I'll keep this issue opened until I know whether documentation changes are needed.

**Comment by captainbrosset** [comment]
What seems to happen is that the IE mode popup blocker does not honor the `--disable-popup-blocker` browser arg at the moment. We have filed a bug on our internal backlog to get this fixed.

In the meantime, here is a possible workaround: use a group policy to disable the popup blocker. E.g.: gpedit (edit group policy) > administrative templates > windows components > internet explorer > internet control panel > security page > internet zone (or your actual zone) > use popup blocker (it must be enabled with the inner dropdown set to disabled).

Hopefully this works for you, and the bug gets resolved soon.
I will close this issue now since the hope is that this will get supported at some point and so no documentation changes should be needed.
