### ISSUE TITLE
IE compatibility List conditions to add a website are confusing

### ISSUE THREAD

**Issue by rik** [MicrosoftDocs/edge-developer#1718]
> The IE compatibility List only adds a website when the following actions occur.
> - Shows an IE user a message suggesting the user should use a different browser for compatibility reasons.
> - Owner requests to add the website to the IE compatibility list.

It is not clear to me if both actions need to occur or only one of them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe5c21b-2296-8b5c-208a-f41eb967c24e
* Version Independent ID: c3722063-7455-5ba9-a78d-102823dfd474
* Content: [Moving users to Microsoft Edge from Internet Explorer - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection)
* Content Source: [microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Nooshu** [comment]
I also have a question around this:
> Shows an IE user a message suggesting the user should use a different browser for compatibility reasons

Is there any information on how this is presented to users using Assistive Technologies? e.g. is it read out by a screen reader?

**Comment by captainbrosset** [comment]
Thank you @rik and @Nooshu for filing this. I agree that the page is pretty confusing.
I think the confusion comes from the way the page describes the message.

> Many modern websites have designs that are incompatible with Internet Explorer. When an Internet Explorer user visits an incompatible public website, the user may get a message. The message states that the website is incompatible with the browser. 

This sentence makes it seem like IE displays the message automatically. This isn't true. What this is saying is that, often, websites will have their own banners saying something like "this site is best viewed with Chrome/Firefox/Edge", for example.

What the `needsedge` list does is auto navigate users of sites that are in this list to Edge. This way users don't have to do it themselves.

So, really, the only thing needed is for website owners to request their sites be added to the list.

About this sentence:

> hows an IE user a message suggesting the user should use a different browser for compatibility reasons.

I need to check this, but perhaps it was added to the doc because the owners of the list do check that the site contains some form of warning message before adding it to the list. But I'm really not sure.

In any case, thanks for the issue, I'll add a task on our backlog to improve this page.

**Comment by captainbrosset** [comment]
Thanks for the issue @rik and @Nooshu. I agree this page is confusing. So confusing that I had first typed in an answer, only to realize that I had it wrong. So I'll need to do more research, but I agree that this needs improvements.

**Comment by captainbrosset** [comment]
Here is what I found out:

- Anyone can request their site to be added to the list by following [these instructions](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection#request-an-update-to-the-internet-explorer-compatibility-list).
- There is no message from the browser on incompatible websites in IE. However, when the user is redirected to Edge automatically, a UI appears in Edge (as shown in the article).
- Like any other part of the browser UI, the message that appears in Edge is accessible and, in particular, will be read by screen readers.

**Comment by rik** [comment]
> Anyone can request their site to be added to the list by following [these instructions](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection#request-an-update-to-the-internet-explorer-compatibility-list).

To make sure I understand, this means that a website owner can request addition to the list, even if the website has no UI suggesting the user should use a different browser, right?
