### ISSUE TITLE
Costs

### ISSUE THREAD

**Issue by SteveALee** [MicrosoftDocs/edge-developer#174]
The documentation for getting started adding PWA says I need to purchase a store dev account which I did. However if you automatically ingest PWAs surely there can be no charge for inclusion? 

Also, I now find out you charge 30% (or 15%) for all user purchases! I'm not happy with that much at all. I'm enriching your ecosystem, which to be fair - needs it. We need some docs on how to switch the way we charge people depending on if they purchase via your store or directly from us (or indeed another store - it's a PWA after all). You T&C seem to indicate you expect us to only sell via your store, which is obviously nonsense.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ba583c8-c78b-49de-a68a-4fbc7a2bb568
* Version Independent ID: e71db58c-e513-eefd-3f4d-2644b88f405d
* Content: [Progressive Web Apps in the Microsoft Store - Microsoft Edge Development](https://docs.microsoft.com/en-gb/microsoft-edge/progressive-web-apps/microsoft-store#criteria-for-automatic-submission)
* Content Source: [microsoft-edge/progressive-web-apps/microsoft-store.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/microsoft-store.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by erikadoyle** [comment]
Hi @SteveALee, thanks for your suggestions. Correct, there is no charge to include a PWA in the Microsoft Store, and more and more (free, high quality) PWAs are being auto-indexed into it. Purchasing a developer account for the Microsoft Store enables you to proactively submit your PWA to the Store (and optionally charge for it) and also gain dashboard access for app analytics and telemetry data.

Probably the most effective (convenient, cross-platform) monetization options for PWAs are those generally available on the web: "in-app" purchases using Web Payments API (and your preferred payment service provider) and/or advertisements using an advertising platform of your choice.

**Comment by erikadoyle** [comment]
Please let me know if there's a specific place of this doc that was misleading and/or if you have ideas for improvements. Thanks!

**Comment by erikadoyle** [comment]
First, thanks for taking the time to explain your frustration. Let me try to address the points you raised, then see out how to improve the docs to better explain the current status of PWAs on Windows (which is quite likely to evolve alongside the PWA movement on the web).

1. Although the essential features of a PWA (and support for those feature across different browsers/platforms) varies depending on who you ask, you are not alone in saying that "install from browser" (and/or "add to homescreen") is a key PWA scenario for you. The Edge team is looking into this. Here are the relevant UserVoice tickets in case you'd like to add any further comments/suggestions: 
 - https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/13307400-support-progressive-web-apps
 - https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/12416253-provide-apps-mode-for-websites-like-chrome-appli

2. PWAs can run as sites in Microsoft Edge (with service workers, push notifications, and other web standards-based PWA technologies), however they cannot access WinRT APIs as such. To call native WinRT APIs requires you to take the extra step of [making your PWA installable](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/windows-features) by packaging it as a Windows app. Under the hood what's happening is that your PWA runs in the `WWAHost.exe` process (rather than the Edge browser process), which is the runtime for JavaScript-based Windows apps. Running in this process provides your PWA a number of [additional affordances](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps#pwas-on-windows-10).

3. Purchasing a developer account for the Microsoft Store enables you to proactively submit your PWA to the Store (and optionally charge for it). While more and more PWAs are getting auto-indexed into the Store, there's no guarantee if/when any one specific PWA might show up there. Also only free PWAs are being auto-indexed, so you'd want to manually submit your PWA (and designate which regions/markets, etc.) if its something you'd like to charge for up-front. Even if your free PWA was already indexed into the Store, having a developer account would provide you access to the Store Dashboard for app analytics and telemetry data.

Where in the Store agreement are you seeing the restrictions about monetization? I'm not an expert in that area, but I can track down the answer and hopefully amend the docs to be more clear for PWA developers.

**Comment by SteveALee** [comment]
@erikadoyle Thanks for much clarification! I certainly intend to take advantage of the Windows APIs as a store App!

> "install from browser" (and/or "add to homescreen") is a key PWA scenario for you

Well this was an original incentive for PWAs - App like experience using Web tech. Only Install if you use it often. However the Actual UX for installing has not be specced as far as I know which is a drop off really.

> To call native WinRT APIs requires you to take the extra step of making your PWA installable by packaging it as a Windows app.

Of course! I sort of l knew that but hadn;t quite grasped it :) Thanks
So WinRT lives on! :)

> Purchasing a developer account for the Microsoft Store enables you to ...

Again thanks for the explanations :)
I'm thinking of having a free WebApp with in App purchases and then making the Windows version pay up front and/or in App extras. All Depends on build and deploy compexities. The cost/benefit trade off seems to be the effort of integrating somehting like Stripe vs paying MS 1/3 of income.

I'll look for that store agreement stuff and add it in a comment.

Thanks again

**Comment by SteveALee** [comment]
> e. In-App Commerce. You may elect to make In-App Product(s) available for purchase from within your App. New App and In-App Product submissions to the Store are required to use Microsoft's commerce engine to support purchase of any In-App Product(s) that are or can be consumed or used within your App.

I previously read this as saying All in App purchases must use the MS Commerce Engine, even when using any non Store version of the App. I now see that is not true "New App and In-App Product submissions to the Store are" 

I guess we just detect if we're enhanced with WinRT and use MS Commerce if we are, otherwise can use somehting else.

**Comment by erikadoyle** [comment]
Ah, I see--thank you @SteveALee! I'll confirm this is the case and if I learn anything new will update this thread (and the docs).

**Comment by istudiomobile** [comment]
Hi, I developed a HWA that is intended to be published in the Windows 10 store to make it installable on devices. Is there a way to make a trial version of it? ...and allow continous usage after payment is made?

Thanks in advance!
