### ISSUE TITLE
Missing `Proxy` API

### ISSUE THREAD

**Issue by tuxzz** [MicrosoftDocs/edge-developer#175]
On the [Microsoft Edge extension API roadmap](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/extension-api-roadmap) page, the `Proxy` API is missing.
But many useful extensions such as SwitchyOmega need it.
Does this mean this API is explicitly under consideration, planned, rejected, or it's under construction?

**Comment by metorm** [comment]
Yeah, there are lots of users who need to visit different sites via different proxies. Using a *.pac file is not convenient enough, especially when you have to switch the option rapidly.
Believe me, that is not for developing purposes, but for regular users (e.g. for those in the mainland China).

This may be the key reason which dives the users to chose Chrome or Firefox rather than Edge. At least for me.

**Comment by Ruikuan** [comment]
Yes. I have to use Chrome on my Surface Pro though it's not good for touch gesture. Edge performs very well, but I can't bear visiting websites without auto switch proxies.

**Comment by gebansal** [comment]
Considering its an old thread and we have rolled out a new Chromium-based Edge browser, I'll go ahead and close it. If you still are facing any issues, please feel free to reopen this issue or file a new one.
