### ISSUE TITLE
Does Not Work Under Windows 11, VS2022 and Net6

### ISSUE THREAD

**Issue by markolbert** [MicrosoftDocs/edge-developer#1781]
The documentation appears to be badly out of date as it relates to Windows 11, VS2022 and Net6. I can place a WebView2 control on an XAML surface, run the apps with no problem...and it refuses to display anything. 

Maybe it just doesn't like www.microsoft.com :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6747d603-e773-dec7-7580-f18f4365cec9
* Version Independent ID: 5f7cd45b-5739-ad85-4b61-c9f94921df98
* Content: [Get started with WebView2 in WinUI 3 (Windows App SDK) apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui)
* Content Source: [microsoft-edge/webview2/get-started/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/get-started/winui.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for filing this issue. Sorry about this. 
Maybe @champnic can help with this. If it turns out to be a bug either in your code or in WebView2, then I'd suggest moving the discussion to the WebView2Feedback repo: https://github.com/MicrosoftEdge/WebView2Feedback/issues
But, if there is indeed outdated documentation to be updated, let's keep this issue open here.

**Comment by captainbrosset** [comment]
Closing as inactive. Please feel free to add more information if you have any and we can re-open the issue.
