### ISSUE TITLE
Glitch instructions outdates

### ISSUE THREAD

**Issue by mipradhan** [MicrosoftDocs/edge-developer#1844]
Glitch doesn't have options like - "show" - this doc needs an update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7af36f2d-2484-c91c-fb12-e7578e806a74
* Version Independent ID: b3314d62-4834-f737-0e6a-8ab762435fae
* Content: [Get started with HTML and the DOM - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/beginners/html)
* Content Source: [microsoft-edge/devtools-guide-chromium/beginners/html.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/beginners/html.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reporting this! Indeed, it looks like the Glitch UI has changed since this tutorial was made. We've had it on our backlog to refresh this tutorial for some time already, so thanks for confirming that it does need an update.
We'll keep this issue open and report back here once we've fixed this.

**Comment by captainbrosset** [comment]
This can now be closed! Yay! I merged some changes in #2074 that removed the glitch demo altogether from this page. Instructions should now be correct.
