### ISSUE TITLE
PWA Store listing shows misleading information

### ISSUE THREAD

**Issue by pdfisk** [MicrosoftDocs/edge-developer#1870]
I have successfully submitted a PWA application to the Microsoft store.

 Here is what is shown in the store listings:

> [!IMPORTANT]
> This app can
> Access all your files, peripheral devices, apps, programs and registry
> Access your Internet connection
> Microsoft.storeFilter.core.notSupported_8wekyb3d8bbwe

I believe that this information will lead clients to believe that the application cannot be installed safely.

Is there any way to avoid this or should I use UWP packaging with WebView2 instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 510619b0-1ad1-47e6-b199-0cb99025d54b
* Version Independent ID: 7d4432c8-45fa-7670-7b6b-1d9e289037b3
* Content: [The user experience of PWAs - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/ux)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/ux.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/ux.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reaching out. Let me ask @aarongustafson for help here. Aaron, is there anything that needs to be changed, perhaps in the manifest, to improve the store listing?

**Comment by JudahGabriel** [comment]
Hi, I work on PWAs and the Store at Microsoft, I might be able to help.

PWAs in the Store use the [Hosted App Model](https://blogs.windows.com/windowsdeveloper/2020/03/19/hosted-app-model), where a host app (in this case, Edge) runs a client app (in this case, your PWA).

In this model, native executables are invoked, which means full trust is required.

That's why the Store says full trust is required: because it's launching a native executable (Edge) to run your app.

That said, we recognize this is misleading to users: PWAs run in the browser's security sandbox, and can't access all your files, the registry, other programs, and other privileged operations.

Because of this, on the Store team we're looking at making a special case for this: if the app is a PWA, the Store could display something less scary, e.g. "This app can ask for additional permissions at runtime" or something.

We'll keep you posted on what we decide.

**Comment by JudahGabriel** [comment]
@pdfisk 

Speaking with the team about this, _where_ are you seeing this?

> [!IMPORTANT]
> This app can
> Access all your files, peripheral devices, apps, programs and registry
> Access your Internet connection
> Microsoft.storeFilter.core.notSupported_8wekyb3d8bbwe

Where are you seeing that?

Currently, in the Store client, I see:

![image](https://user-images.githubusercontent.com/312936/169411567-b8f64ebb-100c-4622-8e7c-2216b8a545f2.png)

Which is still problematic, though less so.

**Comment by JudahGabriel** [comment]
Update: the team has agreed to address this.
