### ISSUE TITLE
Capability msedge.msedgedriverVersion is wrong

### ISSUE THREAD

**Issue by Bradley501** [MicrosoftDocs/edge-developer#1941]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c37572ac-327b-4497-86aa-117434aafa93
* Version Independent ID: 00c6e970-68d3-c53b-dcf1-67a535e482f8
* Content: [Capabilities and EdgeOptions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/capabilities-edge-options)
* Content Source: [microsoft-edge/webdriver-chromium/capabilities-edge-options.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webdriver-chromium/capabilities-edge-options.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Bradley501** [comment]
What is the correct representation of capability msedge.msedgedriverVersion ?

**Comment by captainbrosset** [comment]
Thanks for reaching @Bradley501. We have recently created a new repository to track issues with EdgeDriver, and I think your question would be better answered there. So could you please create a new issue here instead: https://github.com/MicrosoftEdge/EdgeWebDriver/issues

Thanks a lot! I'll close this issue now. If it turns out that new documentation is required as a result of your discussion on the other repo, then feel free to come back here and comment.
