### ISSUE TITLE
No documentation on RegEx options/flags for search

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/edge-developer#1960]
There's no documentation on how to set options/flags for the regex search, nor any documentations on which options/flags are used by default.

And with RegEx options/flags I mean:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_flags

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5074db57-7412-88c6-70a4-213f96ade8cb
* Version Independent ID: 5074db57-7412-88c6-70a4-213f96ade8cb
* Content: [Find source files for a page using the Search tool - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/search/search-tool)
* Content Source: [microsoft-edge/devtools-guide-chromium/search/search-tool.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/search/search-tool.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for the feedback. My understanding (after looking at how the search tool is implemented) is that the only flag that's available to regular expression search is the case sensitive one. If you click on the `Aa` button next to the `.*` regex button in the toolbar, then that will control whether the regex is executed in case sensitive or insensitive mode.
I don't think any of the other regex flags are supported by this tool.

@Bartolomeus-649 does this help? If so, I agree that the documentation should mention this, so that it's clear how the expression is used for searching.

**Comment by Bartolomeus-649** [comment]
Ok, but which options are on by default?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by captainbrosset** [comment]
I would think that these flags are on by default:

* `g`: global
* `i`: case-insensitive
* `m`: multiline

And the only one you can change is `i` by activating the **Aa** button.

Is this what you expected?
