### ISSUE TITLE
[Error APPHOST9624] PWA Firebase authentication 

### ISSUE THREAD

**Issue by towfiqi** [MicrosoftDocs/edge-developer#213]
Trying to compile an appx by following this doc:
https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/windows-features

Our app is built with Firebase. For user login authentication, firebase loads another window so that users can login with their social accounts. When we try to login through the built pwa, we get this error:

`APPHOST9624: The app can’t use script to load the https://appname.firebaseapp.com/.... url because the url launches another app. Only direct user interaction can launch another app.`

the same issue occurs if we try to redirect user for authentication instead of opening up another window.

I am shocked to find out that there are no guidelines as to how it can be fixed. Without login in to the app, huge number of PWA apps wont work. 

Please share the relevant docs to fix this issue, as I have found none.

**Comment by JudahGabriel** [comment]
Is this still an issue you're hitting? Did you find a workaround?

Since you posted, browsers have been updated to better support POSTing back from external windows, which is what Firebase auth is trying to do. Additionally, the Windows app hosting model has since changed, so that in the near future, PWAs in the Microsoft Store will run through Edge itself, enabling the scenario you're talking about.

Closing this as it's old and obsolete. But, if you're still experiencing an issue, I'd be glad to help walk you through it.
