### ISSUE TITLE
Extension API for search engine management

### ISSUE THREAD

**Issue by aidistan** [MicrosoftDocs/edge-developer#2141]
Is there any extension API for manage search engines？

Edge automatically installs websites with open searches, which makes my search engine list too messy to be under control. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 814d311d-f0c4-12c3-eab2-ec4c73612de3
* Version Independent ID: 621a1702-2d7c-b9fb-8076-50087e4f5a64
* Content: [Supported APIs for Microsoft Edge extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/api-support)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/api-support.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/api-support.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
No, I don't think there is currently an extension API to manage search engines unfortunately.
There are many extensions out there that provide their own search experiences instead. This might be an interesting approach for you. This article might give you some ideas: https://www.wired.com/story/9-browser-extensions-search-the-web-better/

Hope you find what you are looking for. Closing this issue for now since there is no documentation change that we need to track here.
Feel free to keep on discussing though.

**Comment by aidistan** [comment]
Thanks for the reply and the info. Sorry for asking at the wrong place.
