### ISSUE TITLE
WHAT?!?  It's a web app for God's sake.

### ISSUE THREAD

**Issue by dguedry** [MicrosoftDocs/edge-developer#220]
Just an FYI, PWAs are actually web apps.  What on Earth does code compilation have to do with the price of tea in China?  What IS THIS? I need to somehow "compile" my PWA webapp using Visual Studio?  That makes no sense.  Just give a place I can submit the URL.  Good Lord!  Talk about unnecessary complexities.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c306f3b9-d287-beba-eb3b-513e58df2440
* Version Independent ID: 787855c5-24d2-b772-e4c3-ce43118e5adb
* Content: [Tailor your PWA for Windows - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/windows-features#feedback)
* Content Source: [microsoft-edge/progressive-web-apps/windows-features.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/progressive-web-apps/windows-features.md)
* Product: **microsoft-edge**
* GitHub Login: @erikadoyle
* Microsoft Alias: **edoyle**

**Comment by JudahGabriel** [comment]
To package your PWA for the Microsoft Store, a build step is needed because it's a full-fledged app. (For what it's worth, the same is true for Google Play, MacOS, Samsung Galaxy stores as well.)

That said, I hear you! It should be easier. You said, "Just give a place I can submit the URL."

Ask, and you shall receive: Go to PWABuilder.com and submit your URL. We'll do the building + packaging for you to get your PWA in the Microsoft Store, Google Play Store, etc.

**Comment by Reezaali** [comment]
I'll proceed to close this issue. Thanks.
