### ISSUE TITLE
[Edge WebDriver Docs Feedback]

### ISSUE THREAD

**Issue by mostafakamelomarrslan** [MicrosoftDocs/edge-developer#2213]
![Capture](https://user-images.githubusercontent.com/81367531/192717309-271fe95c-bf0f-4531-8248-456d3aa10dd3.PNG)
i have tried to change this info with javascript as i have changed it with chrome but edge when i make restart it's reset the the options please solve it fast

**Comment by captainbrosset** [comment]
Hi @mostafakamelomarrslan, thanks for reaching out, but I'm a little confused with this issue.

First, the title mentions Edge WebDriver, but then the description of the issue doesn't.
Secondly, you're saying that you're attempting to change the secure DNS setting from JavaScript, but I don't think this is possible at all.

Can you please provide more details about what you're trying to do exactly and why? Thanks.

**Comment by mostafakamelomarrslan** [comment]
I often when I want to change something in the settings I use the JavaScript with Selenium
( ((IJavaScriptExecutor)webdriver).ExecuteScript )
when I use it in chrome browser work well with edge driver when I edit setting if I make refresh all setting reset

**Comment by bwalderman** [comment]
@mostafakamelomarrslan can you share the complete script you are using with Edge and the expected results?

**Comment by mostafakamelomarrslan** [comment]
driver.ExecuteJavaScript("return document.querySelector('input#itemAllowIncognito').click();");

**Comment by mostafakamelomarrslan** [comment]
This code activates the  add-ons in incognito mode || this method work well in google add-ons

**Comment by bwalderman** [comment]
@mostafakamelomarrslan , Edge and Chrome are unique products with their own settings UI. "Incognito" is a Google term for their private browser feature. The similar feature in Edge is called "InPrivate", so you won't find any mentions of "Incognito" in our settings UI. In general, code that manipulates the settings page in one browser should not be expected to work in another.

If you are still interested in toggling Edge settings through edge://settings using WebDriver, you are free to do so, but this is not something we explicitly support. We can't make any guarantees that code targeting the edge://settings page will continue to work as future versions of Edge are released, and the settings UI changes as a result.

**Comment by mostafakamelomarrslan** [comment]
I mean, through JavaScript, I can control the settings in Google. I tried the same method in the Edge browser, which actually activates, but it does not apply, unlike Chrome, this is what I mean

**Comment by captainbrosset** [comment]
Isn't there a way that you could activate the settings you want when starting Edge? Instead of doing it via Selenium by running JavaScript on the Settings page?
I don't know what settings you want to change exactly, but I think you can start Edge with a particular profile, and this profile could contain the settings you want. 
I don't know enough here, so I may be mistaken. But I believe this would be far simpler.

In any case, let's continue the conversation here. I'll close the issue for now, because this repository is about our docs, and this doesn't seem like a docs issue. It could be solved by, either making a fix in Edge to take the setting into account, or a fix in your test, to toggle the setting differently.

Please don't take me closing this issue as a signal that the conversation is ended. Feel free to continue using this place to discuss further. And if any action is identified at the end, I'm happy to redirect it to the right place.
