### ISSUE TITLE
Extension Limit for one developer Account

### ISSUE THREAD

**Issue by 11Ashish11** [MicrosoftDocs/edge-developer#2230]
**Link to the documentation page**: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/create-dev-account

**Description of the issue**: Is there any limit on number of extensions that can be hosted from one developer account or we can host any number of extensions ? 

**Screenshots**: -

**Microsoft Edge version**: -

**Comment by captainbrosset** [comment]
There isn't really a limit to the number of extensions that you can create as a developer in partner center under one account. There might be a very high limit, but I don't know how many it is exactly, and I think it's very high, so that should be sufficient for most use cases.

I hope this answers your question. Thanks!
