### ISSUE TITLE
Set current MSAL token in Request Header and get logged in silently in React App.

### ISSUE THREAD

**Issue by AshokSenTCS** [MicrosoftDocs/edge-developer#2234]
Hi Team,

Could you please help here on below concern - 

I have one react app and the app is having MSAL authentication with Token.
Now, I need to show the react app pages under webview2 in a WPF application. Here the main concern is to do the react app authentication silently. We can say, we need to store the fresh token in local storage every time and need to use that token silently to login silently or without user interaction/pop up and without filling the username and password.

Could you please help here to do the same or give some idea.

I tried below by setting the token in request header but it is not working and login screen is still coming/data is not populating without Login/Token.

** private void WebView_NavigationStarting(object sender, CoreWebView2NavigationStartingEventArgs e)
        {
            e.RequestHeaders.SetHeader("Token", "MyToken");
        }**

**Comment by captainbrosset** [comment]
Hi @AshokSenTCS. Thanks for your question. Since this is more of a WebView support question than feedback about our docs, I would ask you to please open a new issue on this repository instead: https://github.com/MicrosoftEdge/WebView2Feedback/issues

You will most likely get better help on that repo.

Thanks for your understanding.
