### ISSUE TITLE
Support Manifest V2

### ISSUE THREAD

**Issue by keithn** [MicrosoftDocs/edge-developer#2265]
Don't let google push you around, this is a great opportunity for edge, a lot of people are going to be looking to get better browsers when they realize they are now flooded with ads.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ef35cb8-c4f6-0f63-4b42-776655e82152
* Version Independent ID: bff44510-e5b6-e2ed-2d77-d8bb7e87c4a9
* Content: [Migrate an extension from Manifest V2 to V3 - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/migrate-your-extension-from-manifest-v2-to-v3)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/migrate-your-extension-from-manifest-v2-to-v3.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/migrate-your-extension-from-manifest-v2-to-v3.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by kaiserajl** [comment]
Agreed. Don't push people back to other browsers after gaining so much market share with the new Edge project.

**Comment by captainbrosset** [comment]
Thank you for your messages on this topic. Please see [Overview and timelines for migrating to Manifest V3](https://learn.microsoft.com/microsoft-edge/extensions-chromium/developer-guide/manifest-v3) for our latest update on this topic:

> We are aware that Chrome has revised the timelines for Manifest V2 sunset and as of now we will continue to follow Chromium's timelines. We continue to analyze the concerns raised by the extension developers and explore the optimal path for Microsoft Edge Add-ons ecosystem. We will independently decide on MV3 migration timelines for Microsoft Edge Addons and share an update here.

I'll go ahead and close this issue for now, since there is no documentation changes that need to be made in response to this issue. But please feel free to continue using this issue to discuss this topic. Feedback and ideas about this is always welcome and helps us make better products for everyone.

I also want to mention that we have another repository about Microsoft Edge extensions where this can be discussed with the rest of the community: https://github.com/microsoft/MicrosoftEdge-Extensions
