### ISSUE TITLE
[Edge WebDriver Docs Feedback] Edge-IEmode模式使用情况反馈

### ISSUE THREAD

**Issue by joung** [MicrosoftDocs/edge-developer#2276]
场景：
edge使用域策略管理配置，用site.xml设置IE模式相关网站，使用驱动代填的时候，会有相应的提示bar弹出。

使用Edge驱动打开IE模式页面，会有提示：
![image](https://user-images.githubusercontent.com/7401458/199149434-28c0eb71-ef47-4500-af43-a1d095d6a3d8.png)
代码：

                        var edgeOption = new QA.Edge.EdgeOptions();
                        //去除“Microsoft Edge 正在由自动化测试软件控制”提示
                        edgeOption.AddAdditionalEdgeOption("useAutomationExtension", false);
                        edgeOption.AddExcludedArgument("enable-automation");
                        edgeOption.AddExcludedArgument("enable-logging");

                        edgeOption.AddArgument("--start-maximized");
                        edgeOption.AddArgument("--disable-infobars");
                        //忽略证书错误
                        edgeOption.AddArgument("--ignore-certificate-errors");
而使用官方提示方法，IE驱动打开网站，则提示更多：
![image](https://user-images.githubusercontent.com/7401458/199149620-70edb6a7-6c6c-4968-8e6f-f98034d78fe9.png)
代码：

                        var ieOptions = new QA.IE.InternetExplorerOptions();
                        ieOptions.AttachToEdgeChrome = true;

                        ieOptions.IntroduceInstabilityByIgnoringProtectedModeSettings = true;
                        ieOptions.IgnoreZoomLevel = true;
                        ieOptions.EnableNativeEvents = false;
                        
                        ieOptions.EdgeExecutablePath = @"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe";

麻烦问下：
有没有对应的方式，去除掉提示。因为此提示影响用户体验。

**Comment by captainbrosset** [comment]
Thanks for your issue.
It seems to me like the issue described here is more about how Edge works rather than the documentation.
This GitHub repository is about documentation only.

I advise you to copy this issue to create a new one on the EdgeWebDriver feedback repository instead: https://github.com/MicrosoftEdge/EdgeWebDriver

You will have better chances of getting help on this particular issue on that repository instead.
Thanks for your understanding!
