### ISSUE TITLE
"In this article" column should follow viewport when scrolling.

### ISSUE THREAD

**Issue by shanekunz** [MicrosoftDocs/edge-developer#2558]
This is a suggestion for probably many Microsoft docs, but the right column "In this article" should follow you when you scroll down.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42ed05ac-9e2a-0809-47fb-75919b50d4ba
* Version Independent ID: 00e0f6cf-74f8-29fa-3ac0-78291fd5f428
* Content: [Network features reference - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/reference)
* Content Source: [microsoft-edge/devtools-guide-chromium/network/reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/network/reference.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
I agree that this would be pretty useful. This isn't the right repository for this though. As you correctly pointed out, this applies to other docs sites too, since they're all based on the same template.

@Reezaali do you know what is the correct place for someone to report bugs or ask for feature requests about the learn.microsoft.com front-end?
