### ISSUE TITLE
[DevTools Docs Feedback]

### ISSUE THREAD

**Issue by zggithu** [MicrosoftDocs/edge-developer#2700]
使用wevview2控件  访问网站时候，网站一致在加载，一直在转圈，请问如何配置解决呢？
使用Edge是可以正常访问的
地址为： https://www.188-sb.com

**Comment by captainbrosset** [comment]
English translation: 

> When using the wevview2 control to access the website, the website is loading consistently and keeps turning in circles. How to configure it?
> Using Edge can be accessed normally
> The address is: https://www.188-sb.com

Thanks for reaching out. Since your question isn't about the documentation of WebView2, but instead about WebView2 itself, can you please open a new issue on the WebView2 feedback repository instead?
Here is the repository to create the new issue: https://github.com/MicrosoftEdge/WebView2Feedback

Thanks for your understanding.
