### ISSUE TITLE
sidebar api not working

### ISSUE THREAD

**Issue by icedoom** [MicrosoftDocs/edge-developer#2731]
[Enter feedback here]
here is the `manifest.json`:
```
  "side_panel": {
    "default_path": "sidebar.html"
  },
  "permissions": [
    "sidePanel"
  ],
```
and the sidebar.html is in the root path.
the extension installed correctly. but when I click  the icon in the toolbar. nothing happened. 
my edge version:  115.0.1901.183  (arm64)

I tried this extension into chrome. nothing happened too.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da36f7f8-33c8-ed0d-8b22-3004fb875c7f
* Version Independent ID: da36f7f8-33c8-ed0d-8b22-3004fb875c7f
* Content: [Extensions in the Microsoft Edge sidebar - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/sidebar)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/sidebar.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/developer-guide/sidebar.md)
* Product: **microsoft-edge**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#45930277

**Comment by captainbrosset** [comment]
That's odd, your code snippet seems correct.

How are you installing the extension locally? 
Are you getting any errors on this page edge://extensions/ ?

**Comment by mikehoffms** [comment]
work item AB#45930277

**Comment by mikehoffms** [comment]
@icedoom 

For the sidebar to open when you click the extension icon in the toolbar, you need to first enable that behavior by adding this additional code:
https://learn.microsoft.com/microsoft-edge/extensions-chromium/developer-guide/sidebar#enable-the-extensions-shortcut-icon-to-open-the-sidebar

After adding that code, there should be an icon that appears in the extensions menu that you can click to open the sidebar, as in the first screenshot in the following section:
https://learn.microsoft.com/microsoft-edge/extensions-chromium/developer-guide/sidebar#opening-the-extension-in-the-sidebar

You might need to use Edge Canary or Edge Dev, for this API to work, because this API has only been rolled out to _some_ machines in Edge Stable.  In your Edge Stable, if you don't see the sidebar icon in the extensions menu, try Edge Canary or Edge Dev instead.

To install Edge Beta/Dev/Canary: https://www.microsoft.com/en-us/edge/download/insider

If Canary or Dev doesn't work for you, as an alternative test approach, if you don't see the sidebar icon in the extensions menu, you can use this command-line flag to try out the API in Edge Stable: 
--enable-features=msExtensionSidePanelSupport

**Comment by icedoom** [comment]
> @icedoom
> 
> For the sidebar to open when you click the extension icon in the toolbar, you need to first enable that behavior by adding this additional code: https://learn.microsoft.com/microsoft-edge/extensions-chromium/developer-guide/sidebar#enable-the-extensions-shortcut-icon-to-open-the-sidebar
> 
> After adding that code, there should be an icon that appears in the extensions menu that you can click to open the sidebar, as in the first screenshot in the following section: https://learn.microsoft.com/microsoft-edge/extensions-chromium/developer-guide/sidebar#opening-the-extension-in-the-sidebar
> 
> You might need to use Edge Canary or Edge Dev, for this API to work, because this API has only been rolled out to _some_ machines in Edge Stable. In your Edge Stable, if you don't see the sidebar icon in the extensions menu, try Edge Canary or Edge Dev instead.
> 
> To install Edge Canary or Edge Dev: https://www.microsoft.com/en-us/edge/download/insider
> 
> If Canary or Dev doesn't work for you, as an alternative test approach, if you don't see the sidebar icon in the extensions menu, you can use this command-line flag to try out the API in Edge Stable: --enable-features=msExtensionSidePanelSupport

thanks for your answer.  

I've got Microsoft applied. 

https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/sidebar

this is a  forthcoming feature. so it is not the right time for now.

**Comment by mikehoffms** [comment]
@icedoom - A clarification from Dev about the 2nd paragraph in my reply above:

The icon in the extensions menu to open the sidebar would appear with the developer's current code itself. 
If the additional code is added, then apart from this icon, the developer's original expected behavior will also work (the sidebar will open when the extension's own icon in the toolbar is clicked).
