### ISSUE TITLE
PWA widgets isn't working

### ISSUE THREAD

**Issue by tanmay-veer** [MicrosoftDocs/edge-developer#2763]
**Link to the documentation page**: The URL to the page.  (_probably https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/widgets - mh_)

**Description of the issue**: Can i use any pwa in widgets like "PWAmp is a music player PWA demo application that defines a widget. The PWAmp widget lets users visualize the current song and play the previous or next songs."
Because i tried various pwa like devdocs.io etc but it isn't working.

**Screenshots**: If applicable, add screenshots to help explain the issue.

**Microsoft Edge version**: If the issue occurs with a specific version of Microsoft Edge.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

AB#45930094

**Comment by mikehoffms** [comment]
work item AB#45930094 @captainbrosset

**Comment by mikehoffms** [comment]
@tanmay-veer - This Issue thread is the best place for discussion, as far as I know.  Also try searching web.  @captainbrosset should be able to join this discussion probably next week.

**Comment by amandabaker** [comment]
@tanmay-veer -- You technically don't put an existing PWA into a widget. Instead, the PWA developer must build the widget experience using the web app manifest, Adaptive Card templates, and JavaScript. I checked devdocs.io, and I don't see the `widgets` member defined in their web app manifest, so you're not seeing a widget because they haven't built support for one yet. You can try the demo mentioned in the documentation if you want to see what a widget could look like: https://microsoftedge.github.io/Demos/pwamp/ 

> Also do i have to code in c++ c# to make native widgets which can be installed from store ?

Nope, no C++/C# is required to build a PWA-backed widget and ship through the store. Once you have produced your widget and can successfully install and run your widget from a public endpoint (the tool doesn't work with localhost), you can package your app using [PWABuilder.com](https://www.pwabuilder.com/) and ship the app to the store without any additional code.

**Comment by mikehoffms** [comment]
This Issue didn't get auto-closed.

[PR 2774](https://github.com/MicrosoftDocs/edge-developer/pull/2774) is live (Clarify building a widget PWA experience). 
Evidence: 
* Has new section "Requires building a custom widget for the PWA".
https://learn.microsoft.com/microsoft-edge/progressive-web-apps-chromium/how-to/widgets#requires-building-a-custom-widget-for-the-pwa
* "Widgets Board" is always init caps.
