### ISSUE TITLE
F12 C:\Windows\SysWOW64\F12\IEChooser.exe not work - black screen

### ISSUE THREAD

**Issue by gabsummer** [MicrosoftDocs/edge-developer#2788]
Hi,
for a few days now I've been having an error with IEChooser to view code from Edge in IE mode. the problem lies in the fact that, having launched IEChooser and selected the tab of my interest [immage1] , the tool does not open and the icon remains black [immage2].
How can i fix? Do you know a way to restore?
Grazie

Select the Tab:
![261319195-55fef86f-eeb7-4ab3-884f-f709f96528fa](https://github.com/MicrosoftDocs/edge-developer/assets/63022489/48c26719-28c1-436b-9ea5-8768fbf73814)

Tool does not open:
![261319494-6a971907-373c-4888-abec-7bfdc51f3536](https://github.com/MicrosoftDocs/edge-developer/assets/63022489/13995a82-bf71-4140-8fe0-916a29a9711a)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7975d65-1681-6282-da7e-3bb085fb2d26
* Version Independent ID: ddfb95e8-bfb5-6049-769e-e182e02b3705
* Content: [Contact the Microsoft Edge DevTools team - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/contact)
* Content Source: [microsoft-edge/devtools-guide-chromium/contact.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/contact.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thanks for reporting. Since this issue is related to DevTools, please file a bug on our dedicated DevTools repository instead of here.  Here it is: https://github.com/MicrosoftEdge/DevTools
When you do, please provide any additional information that may help reproduce and resolve the issue. For example, the version of Edge that you are using, and (if you can) the URL to the website you are trying to inspect in IEMode.

Thanks for your understanding!
