### ISSUE TITLE
Really dreadful

### ISSUE THREAD

**Issue by simonx222** [MicrosoftDocs/edge-developer#2795]
This page is a really dreadful explanation of what you need to do.  It makes a fairly complex topic much harder to understand than it should be.  To take just one example, in Step 6 you are required to effectively work out what you need to do by looking at a sample.  But the sample uses a horrendously complex template library and does everything asynchronously (using a toxic mixture of lambdas and templates) in a way that is almost impenetrably complex and hard to make sense of for anyone who isn't already totally familiar with the extensive bloatware it uses.  What is needed is a clear explanation of what you need to do.  Not this horrendous garbage.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03b80edf-2bbf-73a6-2f3b-e6d193effdd6
* Version Independent ID: 03b80edf-2bbf-73a6-2f3b-e6d193effdd6
* Content: [Call native-side code from web-side code - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/hostobject?tabs=win32)
* Content Source: [microsoft-edge/webview2/how-to/hostobject.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/hostobject.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for reaching out and providing feedback about this particular page. However, I'll have to close this issue for now as it doesn't adhere to our code of conduct.

This project adopted [the Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/) in order to create a welcoming and inspiring community.

Constructive feedback about what is complex to understand, and what could be made better is very much welcome, but we want to make sure everyone involved here demonstrates empahty, kindness, and engages in a respectful way.

Please feel free to open a new issue where you clearly explain which code samples and lines are confusing and too complex, and (if possible) propose ways in which they could be improved, and please refrain from making derogatory comments.
