### ISSUE TITLE
Edge Console Refused to connect because it violates the Document Security Policy

### ISSUE THREAD

**Issue by cesarorosco** [MicrosoftDocs/edge-developer#2804]
Edge Version: 116.0.1938.54 (Compilación oficial) (64 bits)

The following script in the console give the message:
"Refused to connect to '<URL>' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback."
"Refused to connect to 'http://localhost:8080/api/v1/product/' because it violates the document's Content Security Policy.
 
`const response = await fetch('http://localhost:8080/api/v1/product/', {
  method: 'GET'
})
![imagen](https://github.com/MicrosoftDocs/edge-developer/assets/22416592/c616b0b4-4fd8-433e-a19f-66eeb40fbb56)

console.log(await response.json())`

In chrome works ok. I also try to add the headers: Content-Security-Policy': default-src 'self' but it doesn't work.
In the network console there is no request to the server.

**Comment by captainbrosset** [comment]
Hi, thank you for reaching out.

This repository is for technical documentation only. If I'm understanding your issue correctly, you don't need help with documentation, but with DevTools, or with Edge itself. Which means, here is not the right place for this issue.

I'm not exactly sure what the issue is, but I can offer two suggestions:

1. If you think your code is correct, and it works in Chrome, but not in Edge, and you suspect a web compatibility issue, then you should report this bug to Edge directly. Here's how:

   1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
   2. Click **Help and feedback**.
   3. Click **Send feedback**.

2. If, instead, you need help with this specific error message in the Console, and you think the Console could do a better job at explaining it, then I suggest sending this to the DevTools team. Here's how:
  
   1. Go to https://github.com/MicrosoftEdge/DevTools/issues/
   2. Open a new issue.
