### ISSUE TITLE
Opening Network tab blocks internet connection

### ISSUE THREAD

**Issue by SlyryD** [MicrosoftDocs/edge-developer#2849]
Why does opening the Network tab of dev tools block my internet connection?

Repro:
1. Navigate any webpage
2. Press F12 to open dev tools to the Network tab
3. See net::ERR_INTERNET_DISCONNECTED start popping up
4. Click refresh
5. Page does not load
6. Press F12 to close dev tools
7. Click refresh
8. Page loads

https://github.com/MicrosoftDocs/edge-developer/assets/4186968/975a74a1-fa9a-45ac-b5a6-0932bba139b1

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb159348-28e5-18af-cba2-1dbcde857de0
* Version Independent ID: 1049da4f-215a-0f72-f25a-9eba13bca908
* Content: [Inspect network activity - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/)
* Content Source: [microsoft-edge/devtools-guide-chromium/network/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/network/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Apologies for this. I believe this the same as https://github.com/MicrosoftEdge/DevTools/issues/179 which, fortunately, has already been fixed in Edge 117 and 118 (if I'm not mistaken).
The reason this happens is that this bug was causing the Network throttling option to be set to Offline when DevTools was opened. If this still occurs to you, make sure you don't have an update of Edge that's waiting to be applied. If you do, please update the browser. You can also go to the Network tool in DevTools and change the throttling drop-down value from Offline to No throttling.

Hope that helps. Let me know if the problem persists.

**Comment by SlyryD** [comment]
That was the issue thanks. I was on Edge 117.0.2045.43, though I guess the configuration may have transferred from when I had devtools opened on an earlier version that forced Offline?

**Comment by captainbrosset** [comment]
That's very likely, yes.
