### ISSUE TITLE
Disable\Block progressive web apps from being installed for all users

### ISSUE THREAD

**Issue by Calebs1979** [MicrosoftDocs/edge-developer#2944]
Good day,

I hope you are well,

I have a client with all endpoints which are Intune managed and want to block\prevent progressive web apps from being installed.
Is this possible? I have done some research online and have not found any clues to block PWA's.

Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55284993-672a-b950-38ec-f3e175dfbf93
* Version Independent ID: 0617203d-5c57-037e-74b9-11c025917d07
* Content: [Overview of Progressive Web Apps (PWAs) - Microsoft Edge Development](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/index.md)
* Product: **microsoft-edge**
* Technology: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Hello. I found two Microsoft Edge Enterprise policies that are somewhat related to what you're looking for:

* **WebAppInstallForceList**: https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#webappinstallforcelist
* **WebAppSettings**: https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#webappsettings

They don't do what you're looking for, but I thought I'd mention them in case this helps put you on the right track.

In any case, I suggest reaching out through the Enterprise repository instead of this repo, which is dedicated to web developer docs only. Here is the repo you should ask in: https://github.com/MicrosoftDocs/Edge-Enterprise/

Hope this helps!

**Comment by Calebs1979** [comment]
@captainbrosset Thank you very much for your response and the information provided. I do appreciate it. 

Kind Regards
Caleb
