### ISSUE TITLE
Cross-link two request blocking sections

### ISSUE THREAD

**Issue by pankajparashar** [MicrosoftDocs/edge-developer#2997]
**Link to the documentation page**:
1. https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network-request-blocking/network-request-blocking-tool#block-a-network-request

2. https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/#block-requests

**Description of the issue**:
Docs to block a network request is documented in two different places, one under the **Network** tool and another under **Network request blocking** tool (see the links above). One uses the Command Menu to access the blocking tool, and another one directly accesses the tool from the Activity bar. Rest of the content is the same.

Should these docs be consolidated into one? and then linked from the other section.

AB#48368784

**Comment by captainbrosset** [comment]
Thanks a lot for filing. Let me add this to our backlog for consideration.
One note about duplication: while it's more work to maintain duplicated docs, it sometimes works much better for the reader to have the documentation they need, where they're now, instead of making them context switch to another place. It's on a case by case basis though. So we'll have to review this one and make a call.

**Comment by mikehoffms** [comment]
I plan to cross-link the two sections, via a minor See Also construct.  That will help maintainers & users, regardless of whether the content stays as-is.  Probably keep content as-is, rather than trying to rework it.

**Comment by captainbrosset** [comment]
PR got merged, closing this issue.
