### ISSUE TITLE
[DevTools Docs Feedback]

### ISSUE THREAD

**Issue by zhanglongqi** [MicrosoftDocs/edge-developer#3042]
both of microsoft-edge-beta (122.0.2365.8-1) and microsoft-edge-stable (121.0.2277.98-1)  have the issue of
```
/usr/bin/xdg-icon-resource: 12: Syntax error: end of file unexpected (expecting ";;")
dpkg: error processing package microsoft-edge-stable (--configure):
 installed microsoft-edge-stable package post-installation script subprocess returned error exit status 2
```

![image](https://github.com/MicrosoftDocs/edge-developer/assets/956693/64d1994f-2193-4d2b-a21d-e7acd18504a6)

**Comment by captainbrosset** [comment]
Thank you for reaching out. However, this repository is specific to the Edge developer documentation, and not to the browser itself.
Usually, I would redirect you to using the feedback mechanism of the browser instead. But since you can't install Edge, you won't have access to it. Unless you have another computer where Edge is installed? If so, please do this:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

If you don't have Edge, but have a Windows machine, you can also submit feedback by using the **Feedback Hub** app on Windows.

If the above isn't an option, then please leave feedback about this on the Edge Insider tech community forum: https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider

Thanks for your understanding.
