### ISSUE TITLE
I think the page is outdated

### ISSUE THREAD

**Issue by madhaven** [MicrosoftDocs/edge-developer#3139]
* The documentation talks about a manifest file but that exists only in the `dist` folder. That does not make sense.
  ![image](https://github.com/MicrosoftDocs/edge-developer/assets/37440750/a6b85cb0-5872-4efe-b806-b1a97537f373)
* The app.js file contains only three references to the navigator.
  I was not able to access this API.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a244fe70-67b5-97c9-9bf5-ee88daa3cf2a
* Version Independent ID: 39a6ad7c-1dba-f87b-ded0-4236a80caa55
* Content: [Display content in the title bar - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/window-controls-overlay)
* Content Source: [microsoft-edge/progressive-web-apps-chromium/how-to/window-controls-overlay.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/progressive-web-apps-chromium/how-to/window-controls-overlay.md)
* Service: **microsoft-edge**
* Sub-service: **pwa**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

AB#50475498

**Comment by captainbrosset** [comment]
Thanks for filing this issue. I've added it to our backlog. We'll take a look and try to make the page clearer/more up to date.

**Comment by captainbrosset** [comment]
> * The documentation talks about a manifest file but that exists only in the `dist` folder. That does not make sense.

The manifest file is correctly linked to from the docs: https://github.com/MicrosoftEdge/Demos/blob/main/1DIV/dist/manifest.json
Indeed, it's in the `dist` folder, because it's a static file that doesn't require to be built with WebPack, like the other JS files that are in the `src` folder.

Can you elaborate on what doesn't make sense for you here?

> * The app.js file contains only three references to the navigator.
>   I was not able to access this API.

The app.js file does use the `navigator.windowControlsOverlay` API, as shown here: https://github.com/MicrosoftEdge/Demos/blob/main/1DIV/src/app.js#L299-L301

So, thinking about this again, I'm not sure what's the source of the confusion here. Can you please elaborate on what changes you'd like us to make in order to make this article clearer?

**Comment by madhaven** [comment]
I was of the impression that the manifest file should be on top like in an Electron-app, it was weird to find the manifest in the distributable.

The navigator was still not accessible from my Electron scripts, is there a way for an Electron app to access the Window Controls Overlay?

**Comment by captainbrosset** [comment]
No, the Window Controls Overlay is a PWA feature only.
