### ISSUE TITLE
GET is easy. What about POST

### ISSUE THREAD

**Issue by glassm** [MicrosoftDocs/edge-developer#3197]
I've been attempting to send a POST request with a JSON body. I have tried several times and ways but the request always fails. No errors

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3a9da76-3900-dcfa-6fd7-b0aee45f1aec
* Version Independent ID: f3a9da76-3900-dcfa-6fd7-b0aee45f1aec
* Content: [Compose and send web API requests using the Network Console tool - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network-console/network-console-tool)
* Content Source: [microsoft-edge/devtools-guide-chromium/network-console/network-console-tool.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/devtools-guide-chromium/network-console/network-console-tool.md)
* Service: **microsoft-edge**
* Sub-service: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
Thank you for reaching out. This sounds like a DevTools bug rather than a documentation issue (althought it would be good to add a section about sending POST requests with JSON payloads).

But, to be sure, could you please provide more information about your specific scenario?
Maybe a screenshot of your POST request details in the Network Console tool would be useful. I want to make sure I see how your request is configured.

Also, what happens when the request fails? A screenshot for the after state would be helpful too.

**Comment by glassm** [comment]
Sensitivity Label: Public

Hi Patrick,
    I right-clicked on the web page in the Edge browser and selected the "Clip image to OneNote" Icon. It displayed [cid:8d75aa8b-29fb-435d-b181-814618951b68] .

I selected the "Sign in with a a work ...". Entered my corporate information.

this pop-up appeared

[cid:17958d57-1a2d-4fcf-a1b7-9cbf61af0e4d]

Is this based on my employers policy?

Thank you
Mark

________________________________

**Comment by captainbrosset** [comment]
@glassm I don't think your last comment addresses my request. I don't know the "Clip image to OneNote" feature, and it's not related to DevTools.

**Comment by captainbrosset** [comment]
Closing for lack of reply. Feel free to respond to my earlier questions and we can re-open the issue.

**Comment by mikehoffms** [comment]
AB#52450929
re: section about sending POST requests with JSON payloads
