### ISSUE TITLE
Gone?

### ISSUE THREAD

**Issue by ThiloLangbeinHUK** [MicrosoftDocs/edge-developer#3212]
Edge's built-in password reveal icon seems to be gone...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5949a483-1a4d-0f77-5576-af0a335fc959
* Version Independent ID: 824cf57c-044d-9dac-085a-8bcfd6f2dc15
* Content: [Customize the password reveal button - Microsoft Edge Developer documentation](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal)
* Content Source: [microsoft-edge/web-platform/password-reveal.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/web-platform/password-reveal.md)
* Service: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by captainbrosset** [comment]
I still see it when testing with this special html URL in Edge Canary and Release: `data:text/html,<input type="password">`

![image](https://github.com/MicrosoftDocs/edge-developer/assets/1152698/f38c02a8-24bb-44ef-940b-1f063a2749e1)

Can you check which operating system and Edge version this happened on?

**Comment by ThiloLangbeinHUK** [comment]
It's there - until focus is gone from the field. It doesn't come back again.

**Comment by captainbrosset** [comment]
Thank you for responding with more details. Since this sounds like a bug, could you please report it via the Feedback tool that's available in the Edge browser? Here's how:

1. Click **Settings and more** (the `...` button in the top-right corner of the browser).
2. Click **Help and feedback**.
3. Click **Send feedback**.

Thank you for your understanding.
