### ISSUE TITLE
This guide needs to be updated

### ISSUE THREAD

**Issue by ToosTech-Code** [MicrosoftDocs/edge-developer#391]
This guide needs to be updated based on the new MS Edge browser, none of this information is useful right now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4ba40e-71a3-0e5b-0f6f-c22fe6fb93dd
* Version Independent ID: 7d51bd1b-8f03-9786-3615-cda14732e8a3
* Content: [Adding and removing extensions - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/adding-and-removing-extensions#feedback)
* Content Source: [microsoft-edge/extensions/guides/adding-and-removing-extensions.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions/guides/adding-and-removing-extensions.md)
* Product: **microsoft-edge**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Ska-IsTheBest** [comment]
This might have been published since your comment, but there's a whole new topic for Extensions (Chromium) instead of this Extensions (EdgeHTML) topic.  See this: 
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/alternate-distribution-options
Or any of the topics under 
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/

**Comment by Reezaali** [comment]
Thank you for sharing the updated documents. I'm closing this issue as it appears to be resolved. Thank you.
