### ISSUE TITLE
Examples of MSDN entries of value not yet ported to MDN but already redirecting

### ISSUE THREAD

**Issue by Herst** [MicrosoftDocs/edge-developer#47]
* `-ms-touch-select`: https://msdn.microsoft.com/en-us/library/hh975292.aspx

* `-ms-content-zooming`: https://msdn.microsoft.com/en-us/library/hh771891.aspx

:unamused:

(At least there are short descriptions at <https://msdn.microsoft.com/en-us/library/hh920761.aspx>)

**Comment by erikadoyle** [comment]
Thanks @Herst -- I've temporarily removed the redirects for the -ms- prefix CSS property pages that don't yet have equivalents on MDN (so they will load on MSDN). We are in the process of porting them over in the next few weeks and will then reimplement the redirections.

Hopefully I identified all of them, but if you can't find something you're looking for, don't hesitate to re-open this issue and I'll fix it ASAP. Thanks!

**Comment by andersponders** [comment]
The docs on keyboardevents https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent

talks about IE's implementation being different and helpfully refers me to the msdn documentation to see more, which of course is gone. Can you hook me up with some docs on IE's events implementation?

I gotta say im not sold on redirecting everything before literally all the information that was there is ported. IE is notorious for its quirks and now the official source for information on those quirks is gone. Last couple weeks have been annoying. People ask me "well why doesnt this work on IE" and I have to look around for random ass blog posts from 2008 or whatever to figure it out since the actual docs are gone.

**Comment by erikadoyle** [comment]
Here's an overview on the IE's legacy (deprecated) synthetic events implementation: https://msdn.microsoft.com/en-us/library/dn905219(v=vs.85).aspx

I looked up the MSDN doc linked from that MDN page (initKeyboardEvent), and it doesn't have much beyond what https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/initKeyboardEvent already has. The only difference is that IE's signature is:

KeyboardEvent.initKeyboardEvent(string eventType, bool canBubble, bool cancelable, string viewArg, string keyArg, string locationArg, string modifiersListArg, bool repeat, string locale);

. . . where _Locale_ is the value of the "locale" attribute of the event. Also, here are the possible values for the _modifiersListArg_:

**Alt**

The left or right Alt key is pressed. 

**AltGraph**

The Ctrl and Alt keys are pressed. 

**CapsLock**

The Caps Lock toggle is enabled. 

**Control**

The left or right Ctrl key is pressed. 

**Meta**

The Meta/Control key is pressed. 

**NumLock**

The Num Lock toggle is enabled. 

**Scroll**

The Scroll Lock toggle is enabled. 

**Shift**

The left or right Shift key is pressed. 

**Win**

The left or right Windows logo key is pressed.

**Comment by erikadoyle** [comment]
I'm in the process of copying all that to the MDN page, but stuck at the moment troubleshooting some MDN permission issues with the admins

**Comment by andersponders** [comment]
Thanks - this is helpful!
