### ISSUE TITLE
webdriver doesn't function with DeveloperToolsAllowed set to 1 or 2

### ISSUE THREAD

**Issue by jeff-bb** [MicrosoftDocs/edge-developer#507]
If this is expected behavior, please include it on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107ce527-7b9c-ff4e-e524-a8ebbc1a6714
* Version Independent ID: 6c8de68a-01bf-3426-8427-6daa5dca5f03
* Content: [WebDriver (Chromium) - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium)
* Content Source: [microsoft-edge/webdriver-chromium.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webdriver-chromium.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @zoherghadyali
* Microsoft Alias: **zoghadya**

**Comment by zoherghadyali** [comment]
Hi @jeff-bb! Thank you for using Microsoft Edge and sending us your feedback. I can clarify that when the [DeveloperToolsAvailability](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#developertoolsavailability) Microsoft Edge policy is set to 2, Microsoft Edge Driver will no longer be able to drive Microsoft Edge (Chromium). This is because the new Chromium-based Microsoft Edge Driver requires the DevTools. 

I found this [issue](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2604) on Chromium's public issue tracker. When the DeveloperToolsAvailability policy is set to 1, are you still seeing issues with Microsoft Edge Driver? If so, can you try removing the deprecated DeveloperToolsDisabled policy and add the new DeveloeprToolsAvailability policy with a value of 1?

Definitely let us know how that goes for you!

**Comment by jeff-bb** [comment]
DeveloperToolsDisabled is not defined, only DeveloeprToolsAvailability is. I see that is by design, hence the request to update the documentation to include that information. I wasn't interested in troubleshooting my situation as the documentation feedback is not the place for that.
