### ISSUE TITLE
Undocumented changes in Edge 16

### ISSUE THREAD

**Issue by martinsuchan** [MicrosoftDocs/edge-developer#52]
Wondering, if there is any plan to document currently undocumented changes in deprecated APIs between Edge 15 (15063) and Edge 16 (16299)?  
We just discovered after days of debugging our web app that **window.navigator.pointerEnabled** returns **true** in Edge 15, but it returns **undefined** in Edge 16.
Details about this change are available here: https://github.com/aichi/Touchr/issues/7

**Comment by libbymc** [comment]
Hi - thanks for reporting this! Removing APIs are typically rare, but in general we (try to) document them. This one slipped past our radar as the schema of our IDL files (and diff tools) are currently in churn. We will add it to the [EdgeHTML 16 page](https://aka.ms/devguide_edgehtml_16). The ["pointerEnabled" property has been deprecated since IE11](https://msdn.microsoft.com/en-us/library/dn304886), which generally means that support may be removed at any time, so I guess its time had come. 

As far as feature detection for pointer events, we recommend checking for window.PointerEvent or window.navigator.maxTouchPoints (checking it’s at least 2 to see if it’s a touch supported device). The only purpose of window.navigator.pointerEnabled was for feature detection and that became redundant with other ways to check for the feature - which is why it was never added to the official W3C spec.
