### ISSUE TITLE
Question about unique device identifiers

### ISSUE THREAD

**Issue by adrianghc** [MicrosoftDocs/edge-developer#530]
There are several references to an "identifier unique to your device" throughout this document, including in the sections on "Address bar and suggestions", crashes and diagnostic data, installation, SmartScreen and "websites you visit for product and service improvement". Unfortunately, apart from the crashes, diagnostic data and installation, it is not clear to me, nor is it mentioned in any way, why such a unique identifier is required in addition to the one generated for the current browser installation and used in the same occasions as the device identifier. Could you provide additional details on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbfb8308-c97f-2863-9078-e895d724df3a
* Version Independent ID: f22b4134-86d0-8c78-8642-3ef652e6d8be
* Content: [Microsoft Edge Privacy Whitepaper - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper#smartscreen)
* Content Source: [microsoft-edge/privacy-whitepaper.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/privacy-whitepaper.md)
* Product: **microsoft-edge**
* Technology: **browser**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by lilliankravitz** [comment]
Hi, 
 
Thanks for reading our whitepaper and asking questions. We love your attention and commitment to privacy!
 
The identifier unique to your device is collected with our diagnostic data to keep Microsoft Edge secure, up to date and performing as expected. 
 
Users can send optional diagnostic data about how you use the browser and websites you visit. This data is used to improve Microsoft products and services. It is associated with an identifier unique to your device to keep Microsoft Edge secure, up to date and performing as expected. The identifier additionally allows us to provide controls over your data such as delete functionality.
 
We do not send the identifier unique to your device as part of "Address bar and suggestions" and we have updated the documentation to reflect that.
 
SmartScreen collects an identifier unique to your device for certain machines as part of required service data in order to provide the SmartScreen service. This includes data that makes sure the service is up to date, secure and performing properly. 
 
Hope this helps provide clarity. Please reach out if you have any other questions. 
 
Thanks,
Microsoft Edge Privacy Team!

**Comment by adrianghc** [comment]
Hi,

Thanks for getting back to me and answering my concerns, I appreciate it. Your post does provide some clarity, but something is still unclear or even more so than before:

> SmartScreen collects an identifier unique to your device for certain machines as part of required service data in order to provide the SmartScreen service.

What does "certain machines" mean? And does this mean that this unique identifier is not sent for the "other" machines?

Thank you for your time in any case.
