### ISSUE TITLE
Is it possible to troubleshoot the reason why my PWA is not picked up by the app store

### ISSUE THREAD

**Issue by LukeWood** [MicrosoftDocs/edge-developer#662]
Hey there edge-developer team!

I appreciate your guys' great work in pushing pwas forward!  The docs look great - however it seems my PWA is not being picked up by bings automatic indexing.  Is there any way to trouble shoot and detect specifically *why* my app isn't being picked up?  I'm assuming I'm missing some sort of field in my manifest.json.

the page is:
https://tp-scramble.io

**Comment by JudahGabriel** [comment]
Hi Luke,

Bing is no longer picking up PWAs automatically, due to various issues around quality and legality.

The good news is, publishing your PWA in the Microsoft Store is easy as putting your URL into [pwabuilder.com](https://pwabuilder.com) and then clicking `Build My PWA`. It will generate an APPX package that you can submit to the Microsoft Store.

Also, Microsoft is working on making PWA listings in the Store easier. We'll have more to announce on that later this year.
