### ISSUE TITLE
Windows Server 2012R2?

### ISSUE THREAD

**Issue by MojoDK** [MicrosoftDocs/edge-developer#677]
Will it eventually support Windows Server 2012R2? I have tons of clients logging into 2012R2 via remote desktop and our app need to use a new web control since current Web control is IE11 and outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27602e44-0300-1528-058c-3066f533b98c
* Version Independent ID: f95488e7-ec44-6ced-dc3f-ba8f88c70d31
* Content: [Microsoft Edge WebView 2 for Windows Forms apps - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms#feedback)
* Content Source: [microsoft-edge/webview2/gettingstarted/winforms.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/webview2/gettingstarted/winforms.md)
* Product: **microsoft-edge**
* Technology: **webview**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by Reezaali** [comment]
Hi @MojoDK, thanks for opening this issue. We use this repo for documentation issues. Based on your question, it looks like you need an answer from someone on the engineering team. To get a response from the engineering team, can you open your issue here please?
https://github.com/MicrosoftEdge/WebViewFeedback
I'll go ahead and close this issue now. Thanks.
