### ISSUE TITLE
update remote device 

### ISSUE THREAD

**Issue by behroozbc** [MicrosoftDocs/edge-developer#710]
hi 
i want add my device in remote device but documentation is old now in edge 83 i see this page 
![image](https://user-images.githubusercontent.com/20381616/82751158-a545ef80-9dca-11ea-825d-b2413856b993.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 423e15ae-4f85-e6b4-05a0-e1c3a1c2d448
* Version Independent ID: e8d1d135-b095-dbf7-f3b2-28feace8934e
* Content: [Get Started with Remote Debugging Android Devices - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/remote-debugging/#troubleshooting-devtools-is-not-detecting-the-android-device)
* Content Source: [microsoft-edge/devtools-guide-chromium/remote-debugging/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/devtools-guide-chromium/remote-debugging/index.md)
* Product: **microsoft-edge**
* Technology: **devtools**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by zoherghadyali** [comment]
Hi @behroozbc! Thank you for using Microsoft Edge and for sending us your feedback! I have opened a PR up here https://github.com/MicrosoftDocs/edge-developer/pull/721 that updates the documentation with the correct workflow. I also wanted to let you know that you can use the `edge://inspect` page to start remote debugging instead of the Remote devices tool in the DevTools. Absolutely let us know if you have any issues using the `edge://inspect` page!

**Comment by behroozbc** [comment]
hi @zoherghadyali 
yes i have problem!!! how much i test dont work!
i want share port 4200 and see my angular app in my mobile 
i want read docs about this to troubleshooting  
![image](https://user-images.githubusercontent.com/20381616/83293349-e9892380-a200-11ea-9137-783b8d388c83.png)

**Comment by zoherghadyali** [comment]
Hi @behroozbc! From the screenshot, it looks like you are trying to enable port-forwarding from the `edge://inspect` page. We have some documentation here: https://docs.microsoft.com/microsoft-edge/devtools-guide-chromium/remote-debugging/local-server for doing that. It looks like you've configured the port forwarding settings correctly.

From your screenshot, I don't see a device registered on the `edge://inspect` page. Have you plugged in a device with a USB cable and is it appearing on the `edge://inspect` page? If so, have you tried navigating to `localhost:4200` in a browser on your device? Can you share a screenshot of the device itself? 

It may also be helpful to share diagnostic data from your session of Edge. You can use the Feedback icon in the Microsoft Edge Developer Tools:

**Comment by behroozbc** [comment]
> Hi @behroozbc! From the screenshot, it looks like you are trying to enable port-forwarding from the `edge://inspect` page. We have some documentation here: https://docs.microsoft.com/microsoft-edge/devtools-guide-chromium/remote-debugging/local-server for doing that. It looks like you've configured the port forwarding settings correctly.
> 
> From your screenshot, I don't see a device registered on the `edge://inspect` page. Have you plugged in a device with a USB cable and is it appearing on the `edge://inspect` page? If so, have you tried navigating to `localhost:4200` in a browser on your device? Can you share a screenshot of the device itself?
> 
> It may also be helpful to share diagnostic data from your session of Edge. You can use the Feedback icon in the Microsoft Edge Developer Tools:
> ![image](https://user-images.githubusercontent.com/34316555/83722436-d5269b80-a5f1-11ea-8c28-a8d8f23b0b3a.png)
> and ensure the **Send diagnostic data** checkbox is checked.

for this question :From your screenshot, I don't see a device registered on the edge://inspect page. Have you plugged in a device with a USB cable and is it appearing on the edge://inspect page?
yes i plugged in 
for this :  If so, have you tried navigating to localhost:4200 in a browser on your device?
yes but dont opend page 🙁🙁
for this :Can you share a screenshot of the device itself?
i think i submit feedback form my phone

**Comment by zoherghadyali** [comment]
It seems like the cause of the issue is that your Android device is not being registered on the `edge://inspect` page. Have you followed the instructions here: https://developer.android.com/studio/debug/dev-options to configure your Android device correctly? 

This is what the `edge://inspect` page should look like: 
![image](https://user-images.githubusercontent.com/34316555/85807834-e9008180-b707-11ea-866b-c36a9723b201.png)
once desktop Microsoft Edge is able to successfully connect to the Android Microsoft Edge app. This is my Pixel 4 device but you should see your Android device on this page.

**Comment by behroozbc** [comment]
hi @zoherghadyali 
i fix this bug 
i open Xamarin android project in visual studio then ms edge show my device 😄
but i dont know what visual studio do

**Comment by zoherghadyali** [comment]
Glad to hear @behroozbc! Definitely keep sending us your feedback but it would be helpful if you can use the **Feedback** icon in the Microsoft Edge DevTools. Please ensure "Send diagnostic data" is checked and that your email address is included so that members of the Edge team can get back to you about your feedback!

![image](https://user-images.githubusercontent.com/34316555/85884318-4c85c000-b797-11ea-89b4-4c702b43e73a.png)

**Comment by behroozbc** [comment]
hi @zoherghadyali 
 i have sent it 
my channel is stable 
and i get email form team 3
