### ISSUE TITLE
unable to use options.UseChromium

### ISSUE THREAD

**Issue by milosbobal** [MicrosoftDocs/edge-developer#754]
Hello,

Could You please help me?
...
I installed newer version of Microsoft Edge Browser (Microsoft Edge Chromium) which should supports selenium test automation.
I installed appropriate drivers (correct version) downloaded directly from Microsoft official pages.
I installed correct version of WebDriver language bindings for C#
I followed  step by step guide available on https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium?tabs=c-sharp

result : I was unable to use oprions.UseChromium;

C# example 
var options = new EdgeOptions(); 
options.UseChromium = true; 
var driver = new EdgeDriver(options)

### **not working for me!!!**
**I am unable to find namespace**
using Microsoft.Edge.SeleniumTools;

**Comment by zoherghadyali** [comment]
Hi @milosbobal! So sorry to hear that and happy to help figure out what's going on here. Which version of the Selenium language binding have you added to your project? We recommend using [Selenium 4.0.0-alpha05](https://www.nuget.org/packages/Selenium.WebDriver/4.0.0-alpha05) or later since that version has built-in support for Microsoft Edge. 

However, you can still use the [Selenium 3](https://www.nuget.org/packages/Selenium.WebDriver/3.141.0) package as long as you also add the [Selenium Tools for Microsoft Edge](https://www.nuget.org/packages/Microsoft.Edge.SeleniumTools) package to your project. With this package added, you should be able to set `options.UseChromium = true;`

I've updated our documentation here: https://docs.microsoft.com/microsoft-edge/webdriver-chromium?tabs=c-sharp#use-selenium-3 to include instructions for Selenium 3 if that's the version you are using.

Definitely reply back to let me know if that works for you! Thanks!

**Comment by zoherghadyali** [comment]
Closing as there hasn't been any update on this issue since late June.
