### ISSUE TITLE
UWP Gap in New MS Edge Chromium

### ISSUE THREAD

**Issue by rashadrivera** [MicrosoftDocs/edge-developer#789]
According to this documentation, we need to specify the executable path in our native message host manifest.  In it, we must specify the *path* to our executable.  UWP nativeMessage apps cannot work with the new MS Edge Chromium browser extensions because we can't know the executable path to a UWP app before it is deployed.

Currently, the SecureInput native message demo is obsolete until someone updates it to support chromium extensions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6baf3ba3-2850-707d-fdfc-9b65f88655c7
* Version Independent ID: 661b537b-bba6-cb07-9979-cddcc35421e3
* Content: [Native Messaging - Microsoft Edge Development](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging)
* Content Source: [microsoft-edge/extensions-chromium/developer-guide/native-messaging.md](https://github.com/MicrosoftDocs/edge-developer/blob/master/microsoft-edge/extensions-chromium/developer-guide/native-messaging.md)
* Product: **microsoft-edge-chromium**
* Technology: **extensions**
* GitHub Login: @MSEdgeTeam
* Microsoft Alias: **msedgedevrel**

**Comment by gebansal** [comment]
@rashadrivera We'd request you to please reach out to the Microsoft Edge extensions team at ext_dev_support@microsoft.com for the above issue.

**Comment by gebansal** [comment]
UWP apps are not directly supported but there are workarounds to make them work. It is not recommended to create a UWP app for native messaging because Win32 apps can do everything that UWP apps can and UWP apps are more restrictive in nature.

For a working native messaging example and further clarifications, request you to reach out to the team at ext_dev_support@microsoft.com.
